name: rate_my_movie
description: "Rate My Movie - CatÃ¡logo Pessoal de Filmes (Flutter + Provider + Firebase + TMDb)"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  path: ^1.9.0
  flutter_dotenv: ^5.2.1
  # Firebase (Advanced Option A)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
